apiVersion: stackit.m.crossplane.io/v1beta1
kind: ProviderConfig
metadata:
  name: provider-stackit-config
  namespace: crossplane-system
spec:
  credentials:
    source: Secret
    secretRef:
      name: stackit-credentials
      namespace: crossplane-system
      key: credentials
